package rtr.objects.objectflags;

import java.util.HashMap;
import org.newdawn.slick.SlickException;
import rtr.map.MapTilesLoader;
import rtr.objects.ObjectBase;
import rtr.objects.objectflags.ObjectFlags;
import rtr.objects.objectflags.corruption.CorruptedFireBowTowerFlags;
import rtr.objects.objectflags.corruption.CorruptedFirePhantomDartTowerFlags;
import rtr.objects.objectflags.corruption.CorruptedFirePitFlags;
import rtr.objects.objectflags.corruption.CorruptedGraveyardLargeFlags;
import rtr.objects.objectflags.corruption.CorruptedGraveyardMediumFlags;
import rtr.objects.objectflags.corruption.CorruptedGraveyardSmallFlags;
import rtr.objects.objectflags.corruption.CorruptedIceBowTowerFlags;
import rtr.objects.objectflags.corruption.CorruptedIcePhantomDartTowerFlags;
import rtr.objects.objectflags.corruption.CorruptedLargeFirePitFlags;
import rtr.objects.objectflags.corruption.CorruptedLightningBowTowerFlags;
import rtr.objects.objectflags.corruption.CorruptedLightningPhantomDartTowerFlags;
import rtr.objects.objectflags.corruption.CorruptedPoisonBowTowerFlags;
import rtr.objects.objectflags.corruption.CorruptedPoisonPhantomDartTowerFlags;
import rtr.objects.objectflags.ruins.AncientCullisGateFlags;
import rtr.objects.objectflags.ruins.AncientRadiancePoolFlags;
import rtr.objects.objectflags.towers.AttractTowerFlags;
import rtr.objects.objectflags.towers.BallistaTowerFlags;
import rtr.objects.objectflags.towers.BanishTowerFlags;
import rtr.objects.objectflags.towers.BowTowerFlags;
import rtr.objects.objectflags.towers.BulletTowerFlags;
import rtr.objects.objectflags.towers.ElementalBoltTowerFlags;
import rtr.objects.objectflags.towers.GodTowerFlags;
import rtr.objects.objectflags.towers.PhantomDartTowerFlags;
import rtr.objects.objectflags.towers.RecombobulatorTowerFlags;
import rtr.objects.objectflags.towers.SlingTowerFlags;
import rtr.objects.objectflags.towers.SprayTowerFlags;
import rtr.objects.objectflags.towers.StaticTowerFlags;
import rtr.objects.objectflags.village.AmmoStorageFlags;
import rtr.objects.objectflags.village.AncillaryFlags;
import rtr.objects.objectflags.village.AnimalPenFlags;
import rtr.objects.objectflags.village.ArmorsmithyFlags;
import rtr.objects.objectflags.village.BottlerFlags;
import rtr.objects.objectflags.village.BowyerFlags;
import rtr.objects.objectflags.village.BurnerFlags;
import rtr.objects.objectflags.village.CastleFlags;
import rtr.objects.objectflags.village.ClinicFlags;
import rtr.objects.objectflags.village.CluckerCoopFlags;
import rtr.objects.objectflags.village.CourierStationFlags;
import rtr.objects.objectflags.village.CrylithiumFirePitFlags;
import rtr.objects.objectflags.village.CrystalGolemCombobulatorFlags;
import rtr.objects.objectflags.village.CrystalHarvestryFlags;
import rtr.objects.objectflags.village.CrystalMotivatorFlags;
import rtr.objects.objectflags.village.CrystalStorageFlags;
import rtr.objects.objectflags.village.CrystilleryFlags;
import rtr.objects.objectflags.village.CubeEGolemCombobulatorFlags;
import rtr.objects.objectflags.village.CullisGateFlags;
import rtr.objects.objectflags.village.DoggoHouseFlags;
import rtr.objects.objectflags.village.EquipmentStorageFlags;
import rtr.objects.objectflags.village.EssenceAltarFlags;
import rtr.objects.objectflags.village.EssenceCollectorFlags;
import rtr.objects.objectflags.village.FarmFlags;
import rtr.objects.objectflags.village.FirePitFlags;
import rtr.objects.objectflags.village.FoodStorageFlags;
import rtr.objects.objectflags.village.ForgeFlags;
import rtr.objects.objectflags.village.GoldStorageFlags;
import rtr.objects.objectflags.village.HousingFlags;
import rtr.objects.objectflags.village.KeyShackFlags;
import rtr.objects.objectflags.village.KitchenFlags;
import rtr.objects.objectflags.village.LandfillFlags;
import rtr.objects.objectflags.village.LargeCrylithiumFirePitFlags;
import rtr.objects.objectflags.village.LargeFirePitFlags;
import rtr.objects.objectflags.village.LargeFountainFlags;
import rtr.objects.objectflags.village.LightningRodFlags;
import rtr.objects.objectflags.village.LootBoxFlags;
import rtr.objects.objectflags.village.LumberMillFlags;
import rtr.objects.objectflags.village.LumberShackFlags;
import rtr.objects.objectflags.village.MaintenanceBuildingFlags;
import rtr.objects.objectflags.village.MarketplaceFlags;
import rtr.objects.objectflags.village.MigrationWayStationFlags;
import rtr.objects.objectflags.village.MineralStorageFlags;
import rtr.objects.objectflags.village.MiningFacilityFlags;
import rtr.objects.objectflags.village.MiscellaneousStorageFlags;
import rtr.objects.objectflags.village.OutpostFlags;
import rtr.objects.objectflags.village.ProcessorFlags;
import rtr.objects.objectflags.village.RainCatcherFlags;
import rtr.objects.objectflags.village.RangerLodgeFlags;
import rtr.objects.objectflags.village.ReliquaryFlags;
import rtr.objects.objectflags.village.RockStorageFlags;
import rtr.objects.objectflags.village.RockTumblerFlags;
import rtr.objects.objectflags.village.SmallFountainFlags;
import rtr.objects.objectflags.village.StoneCutteryFlags;
import rtr.objects.objectflags.village.StoneGolemCombobulatorFlags;
import rtr.objects.objectflags.village.ToolsmithyFlags;
import rtr.objects.objectflags.village.TrashCanFlags;
import rtr.objects.objectflags.village.TrashyCubePileFlags;
import rtr.objects.objectflags.village.WaterPurifierFlags;
import rtr.objects.objectflags.village.WayMakerShackFlags;
import rtr.objects.objectflags.village.WellFlags;
import rtr.objects.objectflags.village.WoodGolemCombobulatorFlags;
import rtr.objects.objectflags.village.WoodStorageFlags;
import rtr.objects.objectflags.walls.CrylithiumCurtainWallFlags;
import rtr.objects.objectflags.walls.CrylithiumWallFlags;
import rtr.objects.objectflags.walls.CrylithiumWallGateNSFlags;
import rtr.objects.objectflags.walls.CrylithiumWallGateWEFlags;
import rtr.objects.objectflags.walls.CurtainWallFlags;
import rtr.objects.objectflags.walls.GodWallFlags;
import rtr.objects.objectflags.walls.StoneWallFlags;
import rtr.objects.objectflags.walls.StoneWallGateNSFlags;
import rtr.objects.objectflags.walls.StoneWallGateWEFlags;
import rtr.objects.objectflags.walls.TrashyCubeWallFlags;
import rtr.objects.objectflags.walls.WoodFenceFlags;
import rtr.objects.objectflags.walls.WoodFenceGateNSFlags;
import rtr.objects.objectflags.walls.WoodFenceGateWEFlags;

import rtr.objects.objectflags.village.*;

public class ObjectFlagFactory {
    private HashMap<MapTilesLoader.TileSet, HashMap<ObjectBase.ObjectSubType, ObjectFlags>> objectFlags = new HashMap();

    public ObjectFlagFactory() throws SlickException {
        Enum type;
        Enum[] enumArray = MapTilesLoader.TileSet.values();
        int n = enumArray.length;
        int n2 = 0;
        while (n2 < n) {
            type = enumArray[n2];
            this.objectFlags.put((MapTilesLoader.TileSet)type, new HashMap());
            ++n2;
        }
        enumArray = ObjectBase.ObjectSubType.values();
        n = enumArray.length;
        n2 = 0;
        while (n2 < n) {
            Enum subType = enumArray[n2];
            this.objectFlags.get((Object)MapTilesLoader.TileSet.CORRUPTED_FIRE_BOW_TOWER).put((ObjectBase.ObjectSubType)subType, new CorruptedFireBowTowerFlags(MapTilesLoader.TileSet.CORRUPTED_FIRE_BOW_TOWER, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.CORRUPTED_FIRE_PHANTOM_DART_TOWER).put((ObjectBase.ObjectSubType)subType, new CorruptedFirePhantomDartTowerFlags(MapTilesLoader.TileSet.CORRUPTED_FIRE_PHANTOM_DART_TOWER, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.CORRUPTED_FIRE_PIT).put((ObjectBase.ObjectSubType)subType, new CorruptedFirePitFlags(MapTilesLoader.TileSet.CORRUPTED_FIRE_PIT, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.CORRUPTED_GRAVEYARD_LARGE).put((ObjectBase.ObjectSubType)subType, new CorruptedGraveyardLargeFlags(MapTilesLoader.TileSet.CORRUPTED_GRAVEYARD_LARGE, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.CORRUPTED_GRAVEYARD_MEDIUM).put((ObjectBase.ObjectSubType)subType, new CorruptedGraveyardMediumFlags(MapTilesLoader.TileSet.CORRUPTED_GRAVEYARD_MEDIUM, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.CORRUPTED_GRAVEYARD_SMALL).put((ObjectBase.ObjectSubType)subType, new CorruptedGraveyardSmallFlags(MapTilesLoader.TileSet.CORRUPTED_GRAVEYARD_SMALL, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.CORRUPTED_ICE_BOW_TOWER).put((ObjectBase.ObjectSubType)subType, new CorruptedIceBowTowerFlags(MapTilesLoader.TileSet.CORRUPTED_ICE_BOW_TOWER, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.CORRUPTED_ICE_PHANTOM_DART_TOWER).put((ObjectBase.ObjectSubType)subType, new CorruptedIcePhantomDartTowerFlags(MapTilesLoader.TileSet.CORRUPTED_ICE_PHANTOM_DART_TOWER, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.CORRUPTED_LARGE_FIRE_PIT).put((ObjectBase.ObjectSubType)subType, new CorruptedLargeFirePitFlags(MapTilesLoader.TileSet.CORRUPTED_LARGE_FIRE_PIT, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.CORRUPTED_LIGHTNING_BOW_TOWER).put((ObjectBase.ObjectSubType)subType, new CorruptedLightningBowTowerFlags(MapTilesLoader.TileSet.CORRUPTED_LIGHTNING_BOW_TOWER, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.CORRUPTED_LIGHTNING_PHANTOM_DART_TOWER).put((ObjectBase.ObjectSubType)subType, new CorruptedLightningPhantomDartTowerFlags(MapTilesLoader.TileSet.CORRUPTED_LIGHTNING_PHANTOM_DART_TOWER, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.CORRUPTED_POISON_BOW_TOWER).put((ObjectBase.ObjectSubType)subType, new CorruptedPoisonBowTowerFlags(MapTilesLoader.TileSet.CORRUPTED_POISON_BOW_TOWER, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.CORRUPTED_POISON_PHANTOM_DART_TOWER).put((ObjectBase.ObjectSubType)subType, new CorruptedPoisonPhantomDartTowerFlags(MapTilesLoader.TileSet.CORRUPTED_POISON_PHANTOM_DART_TOWER, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.ANCIENT_CULLIS_GATE).put((ObjectBase.ObjectSubType)subType, new AncientCullisGateFlags(MapTilesLoader.TileSet.ANCIENT_CULLIS_GATE, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.ANCIENT_RADIANCE_POOL).put((ObjectBase.ObjectSubType)subType, new AncientRadiancePoolFlags(MapTilesLoader.TileSet.ANCIENT_RADIANCE_POOL, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.ATTRACT_TOWER).put((ObjectBase.ObjectSubType)subType, new AttractTowerFlags(MapTilesLoader.TileSet.ATTRACT_TOWER, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.ATTRACT_TOWER_UPGRADE_1).put((ObjectBase.ObjectSubType)subType, new AttractTowerFlags(MapTilesLoader.TileSet.ATTRACT_TOWER_UPGRADE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.ATTRACT_TOWER_UPGRADE_2).put((ObjectBase.ObjectSubType)subType, new AttractTowerFlags(MapTilesLoader.TileSet.ATTRACT_TOWER_UPGRADE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.ATTRACT_TOWER_UPGRADE_3).put((ObjectBase.ObjectSubType)subType, new AttractTowerFlags(MapTilesLoader.TileSet.ATTRACT_TOWER_UPGRADE_3, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.BALLISTA_TOWER).put((ObjectBase.ObjectSubType)subType, new BallistaTowerFlags(MapTilesLoader.TileSet.BALLISTA_TOWER, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.BALLISTA_TOWER_UPGRADE_1).put((ObjectBase.ObjectSubType)subType, new BallistaTowerFlags(MapTilesLoader.TileSet.BALLISTA_TOWER_UPGRADE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.BALLISTA_TOWER_UPGRADE_2).put((ObjectBase.ObjectSubType)subType, new BallistaTowerFlags(MapTilesLoader.TileSet.BALLISTA_TOWER_UPGRADE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.BALLISTA_TOWER_UPGRADE_3_FIRE).put((ObjectBase.ObjectSubType)subType, new BallistaTowerFlags(MapTilesLoader.TileSet.BALLISTA_TOWER_UPGRADE_3_FIRE, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.BALLISTA_TOWER_UPGRADE_3_POISON).put((ObjectBase.ObjectSubType)subType, new BallistaTowerFlags(MapTilesLoader.TileSet.BALLISTA_TOWER_UPGRADE_3_POISON, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.BALLISTA_TOWER_UPGRADE_3_ICE).put((ObjectBase.ObjectSubType)subType, new BallistaTowerFlags(MapTilesLoader.TileSet.BALLISTA_TOWER_UPGRADE_3_ICE, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.BANISH_TOWER).put((ObjectBase.ObjectSubType)subType, new BanishTowerFlags(MapTilesLoader.TileSet.BANISH_TOWER, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.BANISH_TOWER_UPGRADE_1).put((ObjectBase.ObjectSubType)subType, new BanishTowerFlags(MapTilesLoader.TileSet.BANISH_TOWER_UPGRADE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.BANISH_TOWER_UPGRADE_2).put((ObjectBase.ObjectSubType)subType, new BanishTowerFlags(MapTilesLoader.TileSet.BANISH_TOWER_UPGRADE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.BANISH_TOWER_UPGRADE_3).put((ObjectBase.ObjectSubType)subType, new BanishTowerFlags(MapTilesLoader.TileSet.BANISH_TOWER_UPGRADE_3, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.BOW_TOWER).put((ObjectBase.ObjectSubType)subType, new BowTowerFlags(MapTilesLoader.TileSet.BOW_TOWER, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.BOW_TOWER_UPGRADE_1).put((ObjectBase.ObjectSubType)subType, new BowTowerFlags(MapTilesLoader.TileSet.BOW_TOWER_UPGRADE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.BOW_TOWER_UPGRADE_2).put((ObjectBase.ObjectSubType)subType, new BowTowerFlags(MapTilesLoader.TileSet.BOW_TOWER_UPGRADE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.BOW_TOWER_UPGRADE_3_FIRE).put((ObjectBase.ObjectSubType)subType, new BowTowerFlags(MapTilesLoader.TileSet.BOW_TOWER_UPGRADE_3_FIRE, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.BOW_TOWER_UPGRADE_3_POISON).put((ObjectBase.ObjectSubType)subType, new BowTowerFlags(MapTilesLoader.TileSet.BOW_TOWER_UPGRADE_3_POISON, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.BOW_TOWER_UPGRADE_3_ICE).put((ObjectBase.ObjectSubType)subType, new BowTowerFlags(MapTilesLoader.TileSet.BOW_TOWER_UPGRADE_3_ICE, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.BULLET_TOWER).put((ObjectBase.ObjectSubType)subType, new BulletTowerFlags(MapTilesLoader.TileSet.BULLET_TOWER, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.BULLET_TOWER_UPGRADE_1).put((ObjectBase.ObjectSubType)subType, new BulletTowerFlags(MapTilesLoader.TileSet.BULLET_TOWER_UPGRADE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.BULLET_TOWER_UPGRADE_2).put((ObjectBase.ObjectSubType)subType, new BulletTowerFlags(MapTilesLoader.TileSet.BULLET_TOWER_UPGRADE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.BULLET_TOWER_UPGRADE_3_FIRE).put((ObjectBase.ObjectSubType)subType, new BulletTowerFlags(MapTilesLoader.TileSet.BULLET_TOWER_UPGRADE_3_FIRE, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.BULLET_TOWER_UPGRADE_3_LIGHTNING).put((ObjectBase.ObjectSubType)subType, new BulletTowerFlags(MapTilesLoader.TileSet.BULLET_TOWER_UPGRADE_3_LIGHTNING, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.BULLET_TOWER_UPGRADE_3_ICE).put((ObjectBase.ObjectSubType)subType, new BulletTowerFlags(MapTilesLoader.TileSet.BULLET_TOWER_UPGRADE_3_ICE, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.ELEMENTAL_BOLT_TOWER).put((ObjectBase.ObjectSubType)subType, new ElementalBoltTowerFlags(MapTilesLoader.TileSet.ELEMENTAL_BOLT_TOWER, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.ELEMENTAL_BOLT_TOWER_UPGRADE_1).put((ObjectBase.ObjectSubType)subType, new ElementalBoltTowerFlags(MapTilesLoader.TileSet.ELEMENTAL_BOLT_TOWER_UPGRADE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.ELEMENTAL_BOLT_TOWER_UPGRADE_2).put((ObjectBase.ObjectSubType)subType, new ElementalBoltTowerFlags(MapTilesLoader.TileSet.ELEMENTAL_BOLT_TOWER_UPGRADE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.ELEMENTAL_BOLT_TOWER_UPGRADE_3_FIRE).put((ObjectBase.ObjectSubType)subType, new ElementalBoltTowerFlags(MapTilesLoader.TileSet.ELEMENTAL_BOLT_TOWER_UPGRADE_3_FIRE, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.ELEMENTAL_BOLT_TOWER_UPGRADE_3_LIGHTNING).put((ObjectBase.ObjectSubType)subType, new ElementalBoltTowerFlags(MapTilesLoader.TileSet.ELEMENTAL_BOLT_TOWER_UPGRADE_3_LIGHTNING, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.ELEMENTAL_BOLT_TOWER_UPGRADE_3_ICE).put((ObjectBase.ObjectSubType)subType, new ElementalBoltTowerFlags(MapTilesLoader.TileSet.ELEMENTAL_BOLT_TOWER_UPGRADE_3_ICE, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.PHANTOM_DART_TOWER).put((ObjectBase.ObjectSubType)subType, new PhantomDartTowerFlags(MapTilesLoader.TileSet.PHANTOM_DART_TOWER, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.PHANTOM_DART_TOWER_UPGRADE_1).put((ObjectBase.ObjectSubType)subType, new PhantomDartTowerFlags(MapTilesLoader.TileSet.PHANTOM_DART_TOWER_UPGRADE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.PHANTOM_DART_TOWER_UPGRADE_2).put((ObjectBase.ObjectSubType)subType, new PhantomDartTowerFlags(MapTilesLoader.TileSet.PHANTOM_DART_TOWER_UPGRADE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.PHANTOM_DART_TOWER_UPGRADE_3_FIRE).put((ObjectBase.ObjectSubType)subType, new PhantomDartTowerFlags(MapTilesLoader.TileSet.PHANTOM_DART_TOWER_UPGRADE_3_FIRE, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.PHANTOM_DART_TOWER_UPGRADE_3_LIGHTNING).put((ObjectBase.ObjectSubType)subType, new PhantomDartTowerFlags(MapTilesLoader.TileSet.PHANTOM_DART_TOWER_UPGRADE_3_LIGHTNING, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.PHANTOM_DART_TOWER_UPGRADE_3_ICE).put((ObjectBase.ObjectSubType)subType, new PhantomDartTowerFlags(MapTilesLoader.TileSet.PHANTOM_DART_TOWER_UPGRADE_3_ICE, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.RECOMBOBULATOR_TOWER).put((ObjectBase.ObjectSubType)subType, new RecombobulatorTowerFlags(MapTilesLoader.TileSet.RECOMBOBULATOR_TOWER, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.RECOMBOBULATOR_TOWER_UPGRADE_1).put((ObjectBase.ObjectSubType)subType, new RecombobulatorTowerFlags(MapTilesLoader.TileSet.RECOMBOBULATOR_TOWER_UPGRADE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.RECOMBOBULATOR_TOWER_UPGRADE_2).put((ObjectBase.ObjectSubType)subType, new RecombobulatorTowerFlags(MapTilesLoader.TileSet.RECOMBOBULATOR_TOWER_UPGRADE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.RECOMBOBULATOR_TOWER_UPGRADE_3).put((ObjectBase.ObjectSubType)subType, new RecombobulatorTowerFlags(MapTilesLoader.TileSet.RECOMBOBULATOR_TOWER_UPGRADE_3, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.SLING_TOWER).put((ObjectBase.ObjectSubType)subType, new SlingTowerFlags(MapTilesLoader.TileSet.SLING_TOWER, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.SLING_TOWER_UPGRADE_1).put((ObjectBase.ObjectSubType)subType, new SlingTowerFlags(MapTilesLoader.TileSet.SLING_TOWER_UPGRADE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.SLING_TOWER_UPGRADE_2).put((ObjectBase.ObjectSubType)subType, new SlingTowerFlags(MapTilesLoader.TileSet.SLING_TOWER_UPGRADE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.SLING_TOWER_UPGRADE_3_EXPLODING).put((ObjectBase.ObjectSubType)subType, new SlingTowerFlags(MapTilesLoader.TileSet.SLING_TOWER_UPGRADE_3_EXPLODING, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.SLING_TOWER_UPGRADE_3_LIGHTNING).put((ObjectBase.ObjectSubType)subType, new SlingTowerFlags(MapTilesLoader.TileSet.SLING_TOWER_UPGRADE_3_LIGHTNING, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.SLING_TOWER_UPGRADE_3_ICE).put((ObjectBase.ObjectSubType)subType, new SlingTowerFlags(MapTilesLoader.TileSet.SLING_TOWER_UPGRADE_3_ICE, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.SPRAY_TOWER).put((ObjectBase.ObjectSubType)subType, new SprayTowerFlags(MapTilesLoader.TileSet.SPRAY_TOWER, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.SPRAY_TOWER_UPGRADE_1).put((ObjectBase.ObjectSubType)subType, new SprayTowerFlags(MapTilesLoader.TileSet.SPRAY_TOWER_UPGRADE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.SPRAY_TOWER_UPGRADE_2).put((ObjectBase.ObjectSubType)subType, new SprayTowerFlags(MapTilesLoader.TileSet.SPRAY_TOWER_UPGRADE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.SPRAY_TOWER_UPGRADE_3_FIRE).put((ObjectBase.ObjectSubType)subType, new SprayTowerFlags(MapTilesLoader.TileSet.SPRAY_TOWER_UPGRADE_3_FIRE, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.SPRAY_TOWER_UPGRADE_3_LIGHTNING).put((ObjectBase.ObjectSubType)subType, new SprayTowerFlags(MapTilesLoader.TileSet.SPRAY_TOWER_UPGRADE_3_LIGHTNING, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.SPRAY_TOWER_UPGRADE_3_ICE).put((ObjectBase.ObjectSubType)subType, new SprayTowerFlags(MapTilesLoader.TileSet.SPRAY_TOWER_UPGRADE_3_ICE, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.STATIC_TOWER).put((ObjectBase.ObjectSubType)subType, new StaticTowerFlags(MapTilesLoader.TileSet.STATIC_TOWER, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.STATIC_TOWER_UPGRADE_1).put((ObjectBase.ObjectSubType)subType, new StaticTowerFlags(MapTilesLoader.TileSet.STATIC_TOWER_UPGRADE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.STATIC_TOWER_UPGRADE_2).put((ObjectBase.ObjectSubType)subType, new StaticTowerFlags(MapTilesLoader.TileSet.STATIC_TOWER_UPGRADE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.STATIC_TOWER_UPGRADE_3).put((ObjectBase.ObjectSubType)subType, new StaticTowerFlags(MapTilesLoader.TileSet.STATIC_TOWER_UPGRADE_3, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.GOD_TOWER).put((ObjectBase.ObjectSubType)subType, new GodTowerFlags(MapTilesLoader.TileSet.GOD_TOWER, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.AMMO_STORAGE).put((ObjectBase.ObjectSubType)subType, new AmmoStorageFlags(MapTilesLoader.TileSet.AMMO_STORAGE, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.AMMO_STORAGE_UPGRADE_1).put((ObjectBase.ObjectSubType)subType, new AmmoStorageFlags(MapTilesLoader.TileSet.AMMO_STORAGE_UPGRADE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.AMMO_STORAGE_UPGRADE_2).put((ObjectBase.ObjectSubType)subType, new AmmoStorageFlags(MapTilesLoader.TileSet.AMMO_STORAGE_UPGRADE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.AMMO_STORAGE_UPGRADE_3).put((ObjectBase.ObjectSubType)subType, new AmmoStorageFlags(MapTilesLoader.TileSet.AMMO_STORAGE_UPGRADE_3, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.AMMO_STORAGE_UPGRADE_4).put((ObjectBase.ObjectSubType)subType, new AmmoStorageFlags(MapTilesLoader.TileSet.AMMO_STORAGE_UPGRADE_4, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.ANCILLARY).put((ObjectBase.ObjectSubType)subType, new AncillaryFlags(MapTilesLoader.TileSet.ANCILLARY, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.ANCILLARY_UPGRADE_1).put((ObjectBase.ObjectSubType)subType, new AncillaryFlags(MapTilesLoader.TileSet.ANCILLARY_UPGRADE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.ANCILLARY_UPGRADE_2).put((ObjectBase.ObjectSubType)subType, new AncillaryFlags(MapTilesLoader.TileSet.ANCILLARY_UPGRADE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.ANCILLARY_UPGRADE_3).put((ObjectBase.ObjectSubType)subType, new AncillaryFlags(MapTilesLoader.TileSet.ANCILLARY_UPGRADE_3, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.ANCILLARY_UPGRADE_4).put((ObjectBase.ObjectSubType)subType, new AncillaryFlags(MapTilesLoader.TileSet.ANCILLARY_UPGRADE_4, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.ANIMAL_PEN).put((ObjectBase.ObjectSubType)subType, new AnimalPenFlags(MapTilesLoader.TileSet.ANIMAL_PEN, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.ANIMAL_PEN_UPGRADE_1).put((ObjectBase.ObjectSubType)subType, new AnimalPenFlags(MapTilesLoader.TileSet.ANIMAL_PEN_UPGRADE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.ANIMAL_PEN_UPGRADE_2).put((ObjectBase.ObjectSubType)subType, new AnimalPenFlags(MapTilesLoader.TileSet.ANIMAL_PEN_UPGRADE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.ARMORSMITHY).put((ObjectBase.ObjectSubType)subType, new ArmorsmithyFlags(MapTilesLoader.TileSet.ARMORSMITHY, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.ARMORSMITHY_UPGRADE_1).put((ObjectBase.ObjectSubType)subType, new ArmorsmithyFlags(MapTilesLoader.TileSet.ARMORSMITHY_UPGRADE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.ARMORSMITHY_UPGRADE_2).put((ObjectBase.ObjectSubType)subType, new ArmorsmithyFlags(MapTilesLoader.TileSet.ARMORSMITHY_UPGRADE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.BOTTLER).put((ObjectBase.ObjectSubType)subType, new BottlerFlags(MapTilesLoader.TileSet.BOTTLER, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.BOTTLER_UPGRADE_1).put((ObjectBase.ObjectSubType)subType, new BottlerFlags(MapTilesLoader.TileSet.BOTTLER_UPGRADE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.BOTTLER_UPGRADE_2).put((ObjectBase.ObjectSubType)subType, new BottlerFlags(MapTilesLoader.TileSet.BOTTLER_UPGRADE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.RANGER_LODGE).put((ObjectBase.ObjectSubType)subType, new RangerLodgeFlags(MapTilesLoader.TileSet.RANGER_LODGE, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.RANGER_LODGE_UPGRADE_1).put((ObjectBase.ObjectSubType)subType, new RangerLodgeFlags(MapTilesLoader.TileSet.RANGER_LODGE_UPGRADE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.RANGER_LODGE_UPGRADE_2).put((ObjectBase.ObjectSubType)subType, new RangerLodgeFlags(MapTilesLoader.TileSet.RANGER_LODGE_UPGRADE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.BURNER).put((ObjectBase.ObjectSubType)subType, new BurnerFlags(MapTilesLoader.TileSet.BURNER, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.BURNER_UPGRADE_1).put((ObjectBase.ObjectSubType)subType, new BurnerFlags(MapTilesLoader.TileSet.BURNER_UPGRADE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.BURNER_UPGRADE_2).put((ObjectBase.ObjectSubType)subType, new BurnerFlags(MapTilesLoader.TileSet.BURNER_UPGRADE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.BOWYER).put((ObjectBase.ObjectSubType)subType, new BowyerFlags(MapTilesLoader.TileSet.BOWYER, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.BOWYER_UPGRADE_1).put((ObjectBase.ObjectSubType)subType, new BowyerFlags(MapTilesLoader.TileSet.BOWYER_UPGRADE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.BOWYER_UPGRADE_2).put((ObjectBase.ObjectSubType)subType, new BowyerFlags(MapTilesLoader.TileSet.BOWYER_UPGRADE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.CASTLE_1).put((ObjectBase.ObjectSubType)subType, new CastleFlags(MapTilesLoader.TileSet.CASTLE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.CASTLE_2).put((ObjectBase.ObjectSubType)subType, new CastleFlags(MapTilesLoader.TileSet.CASTLE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.CASTLE_3).put((ObjectBase.ObjectSubType)subType, new CastleFlags(MapTilesLoader.TileSet.CASTLE_3, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.CASTLE_4).put((ObjectBase.ObjectSubType)subType, new CastleFlags(MapTilesLoader.TileSet.CASTLE_4, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.CASTLE_5).put((ObjectBase.ObjectSubType)subType, new CastleFlags(MapTilesLoader.TileSet.CASTLE_5, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.CASTLE_6).put((ObjectBase.ObjectSubType)subType, new CastleFlags(MapTilesLoader.TileSet.CASTLE_6, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.CASTLE_7).put((ObjectBase.ObjectSubType)subType, new CastleFlags(MapTilesLoader.TileSet.CASTLE_7, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.CASTLE_8).put((ObjectBase.ObjectSubType)subType, new CastleFlags(MapTilesLoader.TileSet.CASTLE_8, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.CASTLE_9).put((ObjectBase.ObjectSubType)subType, new CastleFlags(MapTilesLoader.TileSet.CASTLE_9, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.CASTLE_10).put((ObjectBase.ObjectSubType)subType, new CastleFlags(MapTilesLoader.TileSet.CASTLE_10, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.CASTLE_11).put((ObjectBase.ObjectSubType)subType, new CastleFlags(MapTilesLoader.TileSet.CASTLE_11, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.CASTLE_12).put((ObjectBase.ObjectSubType)subType, new CastleFlags(MapTilesLoader.TileSet.CASTLE_12, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.CASTLE_13).put((ObjectBase.ObjectSubType)subType, new CastleFlags(MapTilesLoader.TileSet.CASTLE_13, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.CASTLE_14).put((ObjectBase.ObjectSubType)subType, new CastleFlags(MapTilesLoader.TileSet.CASTLE_14, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.CASTLE_15).put((ObjectBase.ObjectSubType)subType, new CastleFlags(MapTilesLoader.TileSet.CASTLE_15, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.CLINIC).put((ObjectBase.ObjectSubType)subType, new ClinicFlags(MapTilesLoader.TileSet.CLINIC, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.CLINIC_UPGRADE_1).put((ObjectBase.ObjectSubType)subType, new ClinicFlags(MapTilesLoader.TileSet.CLINIC_UPGRADE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.CLINIC_UPGRADE_2).put((ObjectBase.ObjectSubType)subType, new ClinicFlags(MapTilesLoader.TileSet.CLINIC_UPGRADE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.CLUCKER_COOP).put((ObjectBase.ObjectSubType)subType, new CluckerCoopFlags(MapTilesLoader.TileSet.CLUCKER_COOP, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.CLUCKER_COOP_UPGRADE_1).put((ObjectBase.ObjectSubType)subType, new CluckerCoopFlags(MapTilesLoader.TileSet.CLUCKER_COOP_UPGRADE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.CLUCKER_COOP_UPGRADE_2).put((ObjectBase.ObjectSubType)subType, new CluckerCoopFlags(MapTilesLoader.TileSet.CLUCKER_COOP_UPGRADE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.COURIER_STATION).put((ObjectBase.ObjectSubType)subType, new CourierStationFlags(MapTilesLoader.TileSet.COURIER_STATION, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.COURIER_STATION_UPGRADE_1).put((ObjectBase.ObjectSubType)subType, new CourierStationFlags(MapTilesLoader.TileSet.COURIER_STATION_UPGRADE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.COURIER_STATION_UPGRADE_2).put((ObjectBase.ObjectSubType)subType, new CourierStationFlags(MapTilesLoader.TileSet.COURIER_STATION_UPGRADE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.CRYLITHIUM_FIRE_PIT).put((ObjectBase.ObjectSubType)subType, new CrylithiumFirePitFlags(MapTilesLoader.TileSet.CRYLITHIUM_FIRE_PIT, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.CRYSTAL_GOLEM_COMBOBULATOR).put((ObjectBase.ObjectSubType)subType, new CrystalGolemCombobulatorFlags(MapTilesLoader.TileSet.CRYSTAL_GOLEM_COMBOBULATOR, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.CRYSTAL_GOLEM_COMBOBULATOR_UPGRADE_1).put((ObjectBase.ObjectSubType)subType, new CrystalGolemCombobulatorFlags(MapTilesLoader.TileSet.CRYSTAL_GOLEM_COMBOBULATOR_UPGRADE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.CRYSTAL_GOLEM_COMBOBULATOR_UPGRADE_2).put((ObjectBase.ObjectSubType)subType, new CrystalGolemCombobulatorFlags(MapTilesLoader.TileSet.CRYSTAL_GOLEM_COMBOBULATOR_UPGRADE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.CRYSTAL_GOLEM_COMBOBULATOR_UPGRADE_3_LIGHTNING).put((ObjectBase.ObjectSubType)subType, new CrystalGolemCombobulatorFlags(MapTilesLoader.TileSet.CRYSTAL_GOLEM_COMBOBULATOR_UPGRADE_3_LIGHTNING, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.CRYSTAL_GOLEM_COMBOBULATOR_UPGRADE_3_ICE).put((ObjectBase.ObjectSubType)subType, new CrystalGolemCombobulatorFlags(MapTilesLoader.TileSet.CRYSTAL_GOLEM_COMBOBULATOR_UPGRADE_3_ICE, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.CRYSTAL_GOLEM_COMBOBULATOR_UPGRADE_3_FIRE).put((ObjectBase.ObjectSubType)subType, new CrystalGolemCombobulatorFlags(MapTilesLoader.TileSet.CRYSTAL_GOLEM_COMBOBULATOR_UPGRADE_3_FIRE, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.CRYSTAL_HARVESTRY).put((ObjectBase.ObjectSubType)subType, new CrystalHarvestryFlags(MapTilesLoader.TileSet.CRYSTAL_HARVESTRY, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.CRYSTAL_HARVESTRY_UPGRADE_1).put((ObjectBase.ObjectSubType)subType, new CrystalHarvestryFlags(MapTilesLoader.TileSet.CRYSTAL_HARVESTRY_UPGRADE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.CRYSTAL_HARVESTRY_UPGRADE_2).put((ObjectBase.ObjectSubType)subType, new CrystalHarvestryFlags(MapTilesLoader.TileSet.CRYSTAL_HARVESTRY_UPGRADE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.CRYSTAL_MOTIVATOR).put((ObjectBase.ObjectSubType)subType, new CrystalMotivatorFlags(MapTilesLoader.TileSet.CRYSTAL_MOTIVATOR, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.CRYSTAL_STORAGE).put((ObjectBase.ObjectSubType)subType, new CrystalStorageFlags(MapTilesLoader.TileSet.CRYSTAL_STORAGE, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.CRYSTAL_STORAGE_UPGRADE_1).put((ObjectBase.ObjectSubType)subType, new CrystalStorageFlags(MapTilesLoader.TileSet.CRYSTAL_STORAGE_UPGRADE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.CRYSTAL_STORAGE_UPGRADE_2).put((ObjectBase.ObjectSubType)subType, new CrystalStorageFlags(MapTilesLoader.TileSet.CRYSTAL_STORAGE_UPGRADE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.CRYSTAL_STORAGE_UPGRADE_3).put((ObjectBase.ObjectSubType)subType, new CrystalStorageFlags(MapTilesLoader.TileSet.CRYSTAL_STORAGE_UPGRADE_3, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.CRYSTAL_STORAGE_UPGRADE_4).put((ObjectBase.ObjectSubType)subType, new CrystalStorageFlags(MapTilesLoader.TileSet.CRYSTAL_STORAGE_UPGRADE_4, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.CRYSTILLERY).put((ObjectBase.ObjectSubType)subType, new CrystilleryFlags(MapTilesLoader.TileSet.CRYSTILLERY, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.CRYSTILLERY_UPGRADE_1).put((ObjectBase.ObjectSubType)subType, new CrystilleryFlags(MapTilesLoader.TileSet.CRYSTILLERY_UPGRADE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.CRYSTILLERY_UPGRADE_2).put((ObjectBase.ObjectSubType)subType, new CrystilleryFlags(MapTilesLoader.TileSet.CRYSTILLERY_UPGRADE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.CUBE_E_GOLEM_COMBOBULATOR).put((ObjectBase.ObjectSubType)subType, new CubeEGolemCombobulatorFlags(MapTilesLoader.TileSet.CUBE_E_GOLEM_COMBOBULATOR, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.CUBE_E_GOLEM_COMBOBULATOR_UPGRADE_1).put((ObjectBase.ObjectSubType)subType, new CubeEGolemCombobulatorFlags(MapTilesLoader.TileSet.CUBE_E_GOLEM_COMBOBULATOR_UPGRADE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.CUBE_E_GOLEM_COMBOBULATOR_UPGRADE_2).put((ObjectBase.ObjectSubType)subType, new CubeEGolemCombobulatorFlags(MapTilesLoader.TileSet.CUBE_E_GOLEM_COMBOBULATOR_UPGRADE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.CULLIS_GATE).put((ObjectBase.ObjectSubType)subType, new CullisGateFlags(MapTilesLoader.TileSet.CULLIS_GATE, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.DOGGO_HOUSE).put((ObjectBase.ObjectSubType)subType, new DoggoHouseFlags(MapTilesLoader.TileSet.DOGGO_HOUSE, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.DOGGO_HOUSE_UPGRADE_1).put((ObjectBase.ObjectSubType)subType, new DoggoHouseFlags(MapTilesLoader.TileSet.DOGGO_HOUSE_UPGRADE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.DOGGO_HOUSE_UPGRADE_2).put((ObjectBase.ObjectSubType)subType, new DoggoHouseFlags(MapTilesLoader.TileSet.DOGGO_HOUSE_UPGRADE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.EQUIPMENT_STORAGE).put((ObjectBase.ObjectSubType)subType, new EquipmentStorageFlags(MapTilesLoader.TileSet.EQUIPMENT_STORAGE, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.EQUIPMENT_STORAGE_UPGRADE_1).put((ObjectBase.ObjectSubType)subType, new EquipmentStorageFlags(MapTilesLoader.TileSet.EQUIPMENT_STORAGE_UPGRADE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.EQUIPMENT_STORAGE_UPGRADE_2).put((ObjectBase.ObjectSubType)subType, new EquipmentStorageFlags(MapTilesLoader.TileSet.EQUIPMENT_STORAGE_UPGRADE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.EQUIPMENT_STORAGE_UPGRADE_3).put((ObjectBase.ObjectSubType)subType, new EquipmentStorageFlags(MapTilesLoader.TileSet.EQUIPMENT_STORAGE_UPGRADE_3, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.EQUIPMENT_STORAGE_UPGRADE_4).put((ObjectBase.ObjectSubType)subType, new EquipmentStorageFlags(MapTilesLoader.TileSet.EQUIPMENT_STORAGE_UPGRADE_4, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.ESSENCE_ALTAR).put((ObjectBase.ObjectSubType)subType, new EssenceAltarFlags(MapTilesLoader.TileSet.ESSENCE_ALTAR, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.ESSENCE_ALTAR_UPGRADE_1).put((ObjectBase.ObjectSubType)subType, new EssenceAltarFlags(MapTilesLoader.TileSet.ESSENCE_ALTAR_UPGRADE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.ESSENCE_ALTAR_UPGRADE_2).put((ObjectBase.ObjectSubType)subType, new EssenceAltarFlags(MapTilesLoader.TileSet.ESSENCE_ALTAR_UPGRADE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.ESSENCE_COLLECTOR).put((ObjectBase.ObjectSubType)subType, new EssenceCollectorFlags(MapTilesLoader.TileSet.ESSENCE_COLLECTOR, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.ESSENCE_COLLECTOR_UPGRADE_1).put((ObjectBase.ObjectSubType)subType, new EssenceCollectorFlags(MapTilesLoader.TileSet.ESSENCE_COLLECTOR_UPGRADE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.ESSENCE_COLLECTOR_UPGRADE_2).put((ObjectBase.ObjectSubType)subType, new EssenceCollectorFlags(MapTilesLoader.TileSet.ESSENCE_COLLECTOR_UPGRADE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.FARM).put((ObjectBase.ObjectSubType)subType, new FarmFlags(MapTilesLoader.TileSet.FARM, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.FARM_UPGRADE_1).put((ObjectBase.ObjectSubType)subType, new FarmFlags(MapTilesLoader.TileSet.FARM_UPGRADE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.FARM_UPGRADE_2).put((ObjectBase.ObjectSubType)subType, new FarmFlags(MapTilesLoader.TileSet.FARM_UPGRADE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.FIRE_PIT).put((ObjectBase.ObjectSubType)subType, new FirePitFlags(MapTilesLoader.TileSet.FIRE_PIT, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.FOOD_STORAGE).put((ObjectBase.ObjectSubType)subType, new FoodStorageFlags(MapTilesLoader.TileSet.FOOD_STORAGE, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.FOOD_STORAGE_UPGRADE_1).put((ObjectBase.ObjectSubType)subType, new FoodStorageFlags(MapTilesLoader.TileSet.FOOD_STORAGE_UPGRADE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.FOOD_STORAGE_UPGRADE_2).put((ObjectBase.ObjectSubType)subType, new FoodStorageFlags(MapTilesLoader.TileSet.FOOD_STORAGE_UPGRADE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.FOOD_STORAGE_UPGRADE_3).put((ObjectBase.ObjectSubType)subType, new FoodStorageFlags(MapTilesLoader.TileSet.FOOD_STORAGE_UPGRADE_3, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.FOOD_STORAGE_UPGRADE_4).put((ObjectBase.ObjectSubType)subType, new FoodStorageFlags(MapTilesLoader.TileSet.FOOD_STORAGE_UPGRADE_4, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.FORGE).put((ObjectBase.ObjectSubType)subType, new ForgeFlags(MapTilesLoader.TileSet.FORGE, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.FORGE_UPGRADE_1).put((ObjectBase.ObjectSubType)subType, new ForgeFlags(MapTilesLoader.TileSet.FORGE_UPGRADE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.FORGE_UPGRADE_2).put((ObjectBase.ObjectSubType)subType, new ForgeFlags(MapTilesLoader.TileSet.FORGE_UPGRADE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.GOLD_STORAGE).put((ObjectBase.ObjectSubType)subType, new GoldStorageFlags(MapTilesLoader.TileSet.GOLD_STORAGE, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.GOLD_STORAGE_UPGRADE_1).put((ObjectBase.ObjectSubType)subType, new GoldStorageFlags(MapTilesLoader.TileSet.GOLD_STORAGE_UPGRADE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.GOLD_STORAGE_UPGRADE_2).put((ObjectBase.ObjectSubType)subType, new GoldStorageFlags(MapTilesLoader.TileSet.GOLD_STORAGE_UPGRADE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.GOLD_STORAGE_UPGRADE_3).put((ObjectBase.ObjectSubType)subType, new GoldStorageFlags(MapTilesLoader.TileSet.GOLD_STORAGE_UPGRADE_3, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.GOLD_STORAGE_UPGRADE_4).put((ObjectBase.ObjectSubType)subType, new GoldStorageFlags(MapTilesLoader.TileSet.GOLD_STORAGE_UPGRADE_4, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.HOUSING).put((ObjectBase.ObjectSubType)subType, new HousingFlags(MapTilesLoader.TileSet.HOUSING, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.HOUSING_UPGRADE_1_OCCUPANCY).put((ObjectBase.ObjectSubType)subType, new HousingFlags(MapTilesLoader.TileSet.HOUSING_UPGRADE_1_OCCUPANCY, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.HOUSING_UPGRADE_2_OCCUPANCY).put((ObjectBase.ObjectSubType)subType, new HousingFlags(MapTilesLoader.TileSet.HOUSING_UPGRADE_2_OCCUPANCY, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.HOUSING_UPGRADE_3_OCCUPANCY).put((ObjectBase.ObjectSubType)subType, new HousingFlags(MapTilesLoader.TileSet.HOUSING_UPGRADE_3_OCCUPANCY, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.HOUSING_UPGRADE_4_OCCUPANCY).put((ObjectBase.ObjectSubType)subType, new HousingFlags(MapTilesLoader.TileSet.HOUSING_UPGRADE_4_OCCUPANCY, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.HOUSING_UPGRADE_1_STANDARD).put((ObjectBase.ObjectSubType)subType, new HousingFlags(MapTilesLoader.TileSet.HOUSING_UPGRADE_1_STANDARD, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.HOUSING_UPGRADE_2_STANDARD).put((ObjectBase.ObjectSubType)subType, new HousingFlags(MapTilesLoader.TileSet.HOUSING_UPGRADE_2_STANDARD, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.HOUSING_UPGRADE_3_STANDARD).put((ObjectBase.ObjectSubType)subType, new HousingFlags(MapTilesLoader.TileSet.HOUSING_UPGRADE_3_STANDARD, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.HOUSING_UPGRADE_4_STANDARD).put((ObjectBase.ObjectSubType)subType, new HousingFlags(MapTilesLoader.TileSet.HOUSING_UPGRADE_4_STANDARD, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.HOUSING_UPGRADE_1_QUALITY).put((ObjectBase.ObjectSubType)subType, new HousingFlags(MapTilesLoader.TileSet.HOUSING_UPGRADE_1_QUALITY, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.HOUSING_UPGRADE_2_QUALITY).put((ObjectBase.ObjectSubType)subType, new HousingFlags(MapTilesLoader.TileSet.HOUSING_UPGRADE_2_QUALITY, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.HOUSING_UPGRADE_3_QUALITY).put((ObjectBase.ObjectSubType)subType, new HousingFlags(MapTilesLoader.TileSet.HOUSING_UPGRADE_3_QUALITY, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.HOUSING_UPGRADE_4_QUALITY).put((ObjectBase.ObjectSubType)subType, new HousingFlags(MapTilesLoader.TileSet.HOUSING_UPGRADE_4_QUALITY, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.KEY_SHACK).put((ObjectBase.ObjectSubType)subType, new KeyShackFlags(MapTilesLoader.TileSet.KEY_SHACK, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.KEY_SHACK_UPGRADE_1).put((ObjectBase.ObjectSubType)subType, new KeyShackFlags(MapTilesLoader.TileSet.KEY_SHACK_UPGRADE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.KEY_SHACK_UPGRADE_2).put((ObjectBase.ObjectSubType)subType, new KeyShackFlags(MapTilesLoader.TileSet.KEY_SHACK_UPGRADE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.KEY_SHACK_UPGRADE_3).put((ObjectBase.ObjectSubType)subType, new KeyShackFlags(MapTilesLoader.TileSet.KEY_SHACK_UPGRADE_3, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.KEY_SHACK_UPGRADE_4).put((ObjectBase.ObjectSubType)subType, new KeyShackFlags(MapTilesLoader.TileSet.KEY_SHACK_UPGRADE_4, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.KITCHEN).put((ObjectBase.ObjectSubType)subType, new KitchenFlags(MapTilesLoader.TileSet.KITCHEN, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.KITCHEN_UPGRADE_1).put((ObjectBase.ObjectSubType)subType, new KitchenFlags(MapTilesLoader.TileSet.KITCHEN_UPGRADE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.KITCHEN_UPGRADE_2).put((ObjectBase.ObjectSubType)subType, new KitchenFlags(MapTilesLoader.TileSet.KITCHEN_UPGRADE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.LANDFILL).put((ObjectBase.ObjectSubType)subType, new LandfillFlags(MapTilesLoader.TileSet.LANDFILL, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.LANDFILL_UPGRADE_1).put((ObjectBase.ObjectSubType)subType, new LandfillFlags(MapTilesLoader.TileSet.LANDFILL_UPGRADE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.LANDFILL_UPGRADE_2).put((ObjectBase.ObjectSubType)subType, new LandfillFlags(MapTilesLoader.TileSet.LANDFILL_UPGRADE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.LARGE_CRYLITHIUM_FIRE_PIT).put((ObjectBase.ObjectSubType)subType, new LargeCrylithiumFirePitFlags(MapTilesLoader.TileSet.LARGE_CRYLITHIUM_FIRE_PIT, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.LARGE_FIRE_PIT).put((ObjectBase.ObjectSubType)subType, new LargeFirePitFlags(MapTilesLoader.TileSet.LARGE_FIRE_PIT, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.LARGE_FOUNTAIN).put((ObjectBase.ObjectSubType)subType, new LargeFountainFlags(MapTilesLoader.TileSet.LARGE_FOUNTAIN, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.LIGHTNING_ROD).put((ObjectBase.ObjectSubType)subType, new LightningRodFlags(MapTilesLoader.TileSet.LIGHTNING_ROD, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.LIGHTNING_ROD_UPGRADE_1).put((ObjectBase.ObjectSubType)subType, new LightningRodFlags(MapTilesLoader.TileSet.LIGHTNING_ROD_UPGRADE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.LIGHTNING_ROD_UPGRADE_2).put((ObjectBase.ObjectSubType)subType, new LightningRodFlags(MapTilesLoader.TileSet.LIGHTNING_ROD_UPGRADE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.LOOT_BOX).put((ObjectBase.ObjectSubType)subType, new LootBoxFlags(MapTilesLoader.TileSet.LOOT_BOX, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.LUMBER_MILL).put((ObjectBase.ObjectSubType)subType, new LumberMillFlags(MapTilesLoader.TileSet.LUMBER_MILL, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.LUMBER_MILL_UPGRADE_1).put((ObjectBase.ObjectSubType)subType, new LumberMillFlags(MapTilesLoader.TileSet.LUMBER_MILL_UPGRADE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.LUMBER_MILL_UPGRADE_2).put((ObjectBase.ObjectSubType)subType, new LumberMillFlags(MapTilesLoader.TileSet.LUMBER_MILL_UPGRADE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.LUMBER_SHACK).put((ObjectBase.ObjectSubType)subType, new LumberShackFlags(MapTilesLoader.TileSet.LUMBER_SHACK, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.LUMBER_SHACK_UPGRADE_1).put((ObjectBase.ObjectSubType)subType, new LumberShackFlags(MapTilesLoader.TileSet.LUMBER_SHACK_UPGRADE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.LUMBER_SHACK_UPGRADE_2).put((ObjectBase.ObjectSubType)subType, new LumberShackFlags(MapTilesLoader.TileSet.LUMBER_SHACK_UPGRADE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.MAINTENANCE_BUILDING).put((ObjectBase.ObjectSubType)subType, new MaintenanceBuildingFlags(MapTilesLoader.TileSet.MAINTENANCE_BUILDING, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.MAINTENANCE_BUILDING_UPGRADE_1).put((ObjectBase.ObjectSubType)subType, new MaintenanceBuildingFlags(MapTilesLoader.TileSet.MAINTENANCE_BUILDING_UPGRADE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.MAINTENANCE_BUILDING_UPGRADE_2).put((ObjectBase.ObjectSubType)subType, new MaintenanceBuildingFlags(MapTilesLoader.TileSet.MAINTENANCE_BUILDING_UPGRADE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.MARKETPLACE).put((ObjectBase.ObjectSubType)subType, new MarketplaceFlags(MapTilesLoader.TileSet.MARKETPLACE, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.MARKETPLACE_UPGRADE_1).put((ObjectBase.ObjectSubType)subType, new MarketplaceFlags(MapTilesLoader.TileSet.MARKETPLACE_UPGRADE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.MARKETPLACE_UPGRADE_2).put((ObjectBase.ObjectSubType)subType, new MarketplaceFlags(MapTilesLoader.TileSet.MARKETPLACE_UPGRADE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.MIGRATION_WAY_STATION).put((ObjectBase.ObjectSubType)subType, new MigrationWayStationFlags(MapTilesLoader.TileSet.MIGRATION_WAY_STATION, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.MIGRATION_WAY_STATION_UPGRADE_1).put((ObjectBase.ObjectSubType)subType, new MigrationWayStationFlags(MapTilesLoader.TileSet.MIGRATION_WAY_STATION_UPGRADE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.MIGRATION_WAY_STATION_UPGRADE_2).put((ObjectBase.ObjectSubType)subType, new MigrationWayStationFlags(MapTilesLoader.TileSet.MIGRATION_WAY_STATION_UPGRADE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.MINERAL_STORAGE).put((ObjectBase.ObjectSubType)subType, new MineralStorageFlags(MapTilesLoader.TileSet.MINERAL_STORAGE, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.MINERAL_STORAGE_UPGRADE_1).put((ObjectBase.ObjectSubType)subType, new MineralStorageFlags(MapTilesLoader.TileSet.MINERAL_STORAGE_UPGRADE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.MINERAL_STORAGE_UPGRADE_2).put((ObjectBase.ObjectSubType)subType, new MineralStorageFlags(MapTilesLoader.TileSet.MINERAL_STORAGE_UPGRADE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.MINERAL_STORAGE_UPGRADE_3).put((ObjectBase.ObjectSubType)subType, new MineralStorageFlags(MapTilesLoader.TileSet.MINERAL_STORAGE_UPGRADE_3, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.MINERAL_STORAGE_UPGRADE_4).put((ObjectBase.ObjectSubType)subType, new MineralStorageFlags(MapTilesLoader.TileSet.MINERAL_STORAGE_UPGRADE_4, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.MINING_FACILITY).put((ObjectBase.ObjectSubType)subType, new MiningFacilityFlags(MapTilesLoader.TileSet.MINING_FACILITY, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.MINING_FACILITY_UPGRADE_1).put((ObjectBase.ObjectSubType)subType, new MiningFacilityFlags(MapTilesLoader.TileSet.MINING_FACILITY_UPGRADE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.MINING_FACILITY_UPGRADE_2).put((ObjectBase.ObjectSubType)subType, new MiningFacilityFlags(MapTilesLoader.TileSet.MINING_FACILITY_UPGRADE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.MISCELLANEOUS_STORAGE).put((ObjectBase.ObjectSubType)subType, new MiscellaneousStorageFlags(MapTilesLoader.TileSet.MISCELLANEOUS_STORAGE, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.MISCELLANEOUS_STORAGE_UPGRADE_1).put((ObjectBase.ObjectSubType)subType, new MiscellaneousStorageFlags(MapTilesLoader.TileSet.MISCELLANEOUS_STORAGE_UPGRADE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.MISCELLANEOUS_STORAGE_UPGRADE_2).put((ObjectBase.ObjectSubType)subType, new MiscellaneousStorageFlags(MapTilesLoader.TileSet.MISCELLANEOUS_STORAGE_UPGRADE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.MISCELLANEOUS_STORAGE_UPGRADE_3).put((ObjectBase.ObjectSubType)subType, new MiscellaneousStorageFlags(MapTilesLoader.TileSet.MISCELLANEOUS_STORAGE_UPGRADE_3, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.MISCELLANEOUS_STORAGE_UPGRADE_4).put((ObjectBase.ObjectSubType)subType, new MiscellaneousStorageFlags(MapTilesLoader.TileSet.MISCELLANEOUS_STORAGE_UPGRADE_4, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.OUTPOST).put((ObjectBase.ObjectSubType)subType, new OutpostFlags(MapTilesLoader.TileSet.OUTPOST, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.OUTPOST_UPGRADE_1).put((ObjectBase.ObjectSubType)subType, new OutpostFlags(MapTilesLoader.TileSet.OUTPOST_UPGRADE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.OUTPOST_UPGRADE_2).put((ObjectBase.ObjectSubType)subType, new OutpostFlags(MapTilesLoader.TileSet.OUTPOST_UPGRADE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.PROCESSOR).put((ObjectBase.ObjectSubType)subType, new ProcessorFlags(MapTilesLoader.TileSet.PROCESSOR, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.PROCESSOR_UPGRADE_1).put((ObjectBase.ObjectSubType)subType, new ProcessorFlags(MapTilesLoader.TileSet.PROCESSOR_UPGRADE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.PROCESSOR_UPGRADE_2).put((ObjectBase.ObjectSubType)subType, new ProcessorFlags(MapTilesLoader.TileSet.PROCESSOR_UPGRADE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.RAIN_CATCHER).put((ObjectBase.ObjectSubType)subType, new RainCatcherFlags(MapTilesLoader.TileSet.RAIN_CATCHER, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.RAIN_CATCHER_UPGRADE_1).put((ObjectBase.ObjectSubType)subType, new RainCatcherFlags(MapTilesLoader.TileSet.RAIN_CATCHER_UPGRADE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.RAIN_CATCHER_UPGRADE_2).put((ObjectBase.ObjectSubType)subType, new RainCatcherFlags(MapTilesLoader.TileSet.RAIN_CATCHER_UPGRADE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.RELIQUARY).put((ObjectBase.ObjectSubType)subType, new ReliquaryFlags(MapTilesLoader.TileSet.RELIQUARY, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.RELIQUARY_UPGRADE_1).put((ObjectBase.ObjectSubType)subType, new ReliquaryFlags(MapTilesLoader.TileSet.RELIQUARY_UPGRADE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.RELIQUARY_UPGRADE_2).put((ObjectBase.ObjectSubType)subType, new ReliquaryFlags(MapTilesLoader.TileSet.RELIQUARY_UPGRADE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.ROCK_STORAGE).put((ObjectBase.ObjectSubType)subType, new RockStorageFlags(MapTilesLoader.TileSet.ROCK_STORAGE, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.ROCK_STORAGE_UPGRADE_1).put((ObjectBase.ObjectSubType)subType, new RockStorageFlags(MapTilesLoader.TileSet.ROCK_STORAGE_UPGRADE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.ROCK_STORAGE_UPGRADE_2).put((ObjectBase.ObjectSubType)subType, new RockStorageFlags(MapTilesLoader.TileSet.ROCK_STORAGE_UPGRADE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.ROCK_STORAGE_UPGRADE_3).put((ObjectBase.ObjectSubType)subType, new RockStorageFlags(MapTilesLoader.TileSet.ROCK_STORAGE_UPGRADE_3, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.ROCK_STORAGE_UPGRADE_4).put((ObjectBase.ObjectSubType)subType, new RockStorageFlags(MapTilesLoader.TileSet.ROCK_STORAGE_UPGRADE_4, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.ROCK_TUMBLER).put((ObjectBase.ObjectSubType)subType, new RockTumblerFlags(MapTilesLoader.TileSet.ROCK_TUMBLER, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.ROCK_TUMBLER_UPGRADE_1).put((ObjectBase.ObjectSubType)subType, new RockTumblerFlags(MapTilesLoader.TileSet.ROCK_TUMBLER_UPGRADE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.ROCK_TUMBLER_UPGRADE_2).put((ObjectBase.ObjectSubType)subType, new RockTumblerFlags(MapTilesLoader.TileSet.ROCK_TUMBLER_UPGRADE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.SMALL_FOUNTAIN).put((ObjectBase.ObjectSubType)subType, new SmallFountainFlags(MapTilesLoader.TileSet.SMALL_FOUNTAIN, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.STONE_CUTTERY).put((ObjectBase.ObjectSubType)subType, new StoneCutteryFlags(MapTilesLoader.TileSet.STONE_CUTTERY, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.STONE_CUTTERY_UPGRADE_1).put((ObjectBase.ObjectSubType)subType, new StoneCutteryFlags(MapTilesLoader.TileSet.STONE_CUTTERY_UPGRADE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.STONE_CUTTERY_UPGRADE_2).put((ObjectBase.ObjectSubType)subType, new StoneCutteryFlags(MapTilesLoader.TileSet.STONE_CUTTERY_UPGRADE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.STONE_GOLEM_COMBOBULATOR).put((ObjectBase.ObjectSubType)subType, new StoneGolemCombobulatorFlags(MapTilesLoader.TileSet.STONE_GOLEM_COMBOBULATOR, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.STONE_GOLEM_COMBOBULATOR_UPGRADE_1).put((ObjectBase.ObjectSubType)subType, new StoneGolemCombobulatorFlags(MapTilesLoader.TileSet.STONE_GOLEM_COMBOBULATOR_UPGRADE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.STONE_GOLEM_COMBOBULATOR_UPGRADE_2).put((ObjectBase.ObjectSubType)subType, new StoneGolemCombobulatorFlags(MapTilesLoader.TileSet.STONE_GOLEM_COMBOBULATOR_UPGRADE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.STONE_GOLEM_COMBOBULATOR_UPGRADE_3_LIGHTNING).put((ObjectBase.ObjectSubType)subType, new StoneGolemCombobulatorFlags(MapTilesLoader.TileSet.STONE_GOLEM_COMBOBULATOR_UPGRADE_3_LIGHTNING, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.STONE_GOLEM_COMBOBULATOR_UPGRADE_3_ICE).put((ObjectBase.ObjectSubType)subType, new StoneGolemCombobulatorFlags(MapTilesLoader.TileSet.STONE_GOLEM_COMBOBULATOR_UPGRADE_3_ICE, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.STONE_GOLEM_COMBOBULATOR_UPGRADE_3_FIRE).put((ObjectBase.ObjectSubType)subType, new StoneGolemCombobulatorFlags(MapTilesLoader.TileSet.STONE_GOLEM_COMBOBULATOR_UPGRADE_3_FIRE, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.TOOLSMITHY).put((ObjectBase.ObjectSubType)subType, new ToolsmithyFlags(MapTilesLoader.TileSet.TOOLSMITHY, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.TOOLSMITHY_UPGRADE_1).put((ObjectBase.ObjectSubType)subType, new ToolsmithyFlags(MapTilesLoader.TileSet.TOOLSMITHY_UPGRADE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.TOOLSMITHY_UPGRADE_2).put((ObjectBase.ObjectSubType)subType, new ToolsmithyFlags(MapTilesLoader.TileSet.TOOLSMITHY_UPGRADE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.TRASH_CAN).put((ObjectBase.ObjectSubType)subType, new TrashCanFlags(MapTilesLoader.TileSet.TRASH_CAN, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.TRASH_CAN_UPGRADE_1).put((ObjectBase.ObjectSubType)subType, new TrashCanFlags(MapTilesLoader.TileSet.TRASH_CAN_UPGRADE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.TRASH_CAN_UPGRADE_2).put((ObjectBase.ObjectSubType)subType, new TrashCanFlags(MapTilesLoader.TileSet.TRASH_CAN_UPGRADE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.TRASHY_CUBE_PILE).put((ObjectBase.ObjectSubType)subType, new TrashyCubePileFlags(MapTilesLoader.TileSet.TRASHY_CUBE_PILE, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.WATER_PURIFIER).put((ObjectBase.ObjectSubType)subType, new WaterPurifierFlags(MapTilesLoader.TileSet.WATER_PURIFIER, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.WATER_PURIFIER_UPGRADE_1).put((ObjectBase.ObjectSubType)subType, new WaterPurifierFlags(MapTilesLoader.TileSet.WATER_PURIFIER_UPGRADE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.WATER_PURIFIER_UPGRADE_2).put((ObjectBase.ObjectSubType)subType, new WaterPurifierFlags(MapTilesLoader.TileSet.WATER_PURIFIER_UPGRADE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.WAY_MAKER_SHACK).put((ObjectBase.ObjectSubType)subType, new WayMakerShackFlags(MapTilesLoader.TileSet.WAY_MAKER_SHACK, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.WAY_MAKER_SHACK_UPGRADE_1).put((ObjectBase.ObjectSubType)subType, new WayMakerShackFlags(MapTilesLoader.TileSet.WAY_MAKER_SHACK_UPGRADE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.WAY_MAKER_SHACK_UPGRADE_2).put((ObjectBase.ObjectSubType)subType, new WayMakerShackFlags(MapTilesLoader.TileSet.WAY_MAKER_SHACK_UPGRADE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.WELL).put((ObjectBase.ObjectSubType)subType, new WellFlags(MapTilesLoader.TileSet.WELL, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.WELL_UPGRADE_1).put((ObjectBase.ObjectSubType)subType, new WellFlags(MapTilesLoader.TileSet.WELL_UPGRADE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.WELL_UPGRADE_2).put((ObjectBase.ObjectSubType)subType, new WellFlags(MapTilesLoader.TileSet.WELL_UPGRADE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.WOOD_GOLEM_COMBOBULATOR).put((ObjectBase.ObjectSubType)subType, new WoodGolemCombobulatorFlags(MapTilesLoader.TileSet.WOOD_GOLEM_COMBOBULATOR, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.WOOD_GOLEM_COMBOBULATOR_UPGRADE_1).put((ObjectBase.ObjectSubType)subType, new WoodGolemCombobulatorFlags(MapTilesLoader.TileSet.WOOD_GOLEM_COMBOBULATOR_UPGRADE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.WOOD_GOLEM_COMBOBULATOR_UPGRADE_2).put((ObjectBase.ObjectSubType)subType, new WoodGolemCombobulatorFlags(MapTilesLoader.TileSet.WOOD_GOLEM_COMBOBULATOR_UPGRADE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.WOOD_GOLEM_COMBOBULATOR_UPGRADE_3_LIGHTNING).put((ObjectBase.ObjectSubType)subType, new WoodGolemCombobulatorFlags(MapTilesLoader.TileSet.WOOD_GOLEM_COMBOBULATOR_UPGRADE_3_LIGHTNING, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.WOOD_GOLEM_COMBOBULATOR_UPGRADE_3_ICE).put((ObjectBase.ObjectSubType)subType, new WoodGolemCombobulatorFlags(MapTilesLoader.TileSet.WOOD_GOLEM_COMBOBULATOR_UPGRADE_3_ICE, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.WOOD_GOLEM_COMBOBULATOR_UPGRADE_3_POISON).put((ObjectBase.ObjectSubType)subType, new WoodGolemCombobulatorFlags(MapTilesLoader.TileSet.WOOD_GOLEM_COMBOBULATOR_UPGRADE_3_POISON, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.WOOD_STORAGE).put((ObjectBase.ObjectSubType)subType, new WoodStorageFlags(MapTilesLoader.TileSet.WOOD_STORAGE, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.WOOD_STORAGE_UPGRADE_1).put((ObjectBase.ObjectSubType)subType, new WoodStorageFlags(MapTilesLoader.TileSet.WOOD_STORAGE_UPGRADE_1, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.WOOD_STORAGE_UPGRADE_2).put((ObjectBase.ObjectSubType)subType, new WoodStorageFlags(MapTilesLoader.TileSet.WOOD_STORAGE_UPGRADE_2, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.WOOD_STORAGE_UPGRADE_3).put((ObjectBase.ObjectSubType)subType, new WoodStorageFlags(MapTilesLoader.TileSet.WOOD_STORAGE_UPGRADE_3, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.WOOD_STORAGE_UPGRADE_4).put((ObjectBase.ObjectSubType)subType, new WoodStorageFlags(MapTilesLoader.TileSet.WOOD_STORAGE_UPGRADE_4, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.CRYLITHIUM_WALL).put((ObjectBase.ObjectSubType)subType, new CrylithiumWallFlags(MapTilesLoader.TileSet.CRYLITHIUM_WALL, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.CRYLITHIUM_WALL_GATE_NS).put((ObjectBase.ObjectSubType)subType, new CrylithiumWallGateNSFlags(MapTilesLoader.TileSet.CRYLITHIUM_WALL_GATE_NS, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.CRYLITHIUM_WALL_GATE_WE).put((ObjectBase.ObjectSubType)subType, new CrylithiumWallGateWEFlags(MapTilesLoader.TileSet.CRYLITHIUM_WALL_GATE_WE, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.CRYLITHIUM_CURTAIN_WALL).put((ObjectBase.ObjectSubType)subType, new CrylithiumCurtainWallFlags(MapTilesLoader.TileSet.CRYLITHIUM_CURTAIN_WALL, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.CURTAIN_WALL).put((ObjectBase.ObjectSubType)subType, new CurtainWallFlags(MapTilesLoader.TileSet.CURTAIN_WALL, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.GOD_WALL).put((ObjectBase.ObjectSubType)subType, new GodWallFlags(MapTilesLoader.TileSet.GOD_WALL, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.STONE_WALL).put((ObjectBase.ObjectSubType)subType, new StoneWallFlags(MapTilesLoader.TileSet.STONE_WALL, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.STONE_WALL_GATE_NS).put((ObjectBase.ObjectSubType)subType, new StoneWallGateNSFlags(MapTilesLoader.TileSet.STONE_WALL_GATE_NS, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.STONE_WALL_GATE_WE).put((ObjectBase.ObjectSubType)subType, new StoneWallGateWEFlags(MapTilesLoader.TileSet.STONE_WALL_GATE_WE, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.TRASHY_CUBE_WALL).put((ObjectBase.ObjectSubType)subType, new TrashyCubeWallFlags(MapTilesLoader.TileSet.TRASHY_CUBE_WALL, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.WOOD_FENCE).put((ObjectBase.ObjectSubType)subType, new WoodFenceFlags(MapTilesLoader.TileSet.WOOD_FENCE, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.WOOD_FENCE_GATE_NS).put((ObjectBase.ObjectSubType)subType, new WoodFenceGateNSFlags(MapTilesLoader.TileSet.WOOD_FENCE_GATE_NS, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.WOOD_FENCE_GATE_WE).put((ObjectBase.ObjectSubType)subType, new WoodFenceGateWEFlags(MapTilesLoader.TileSet.WOOD_FENCE_GATE_WE, (ObjectBase.ObjectSubType)subType));

            //qui vanno le aggiunte per i costruttori delle strutture

            //@@Inizio_Aggiunta_Costruttori_Flags

            this.objectFlags.get((Object)MapTilesLoader.TileSet.WOOD_MOTIVATOR).put((ObjectBase.ObjectSubType)subType, new WoodMotivatorFlags(MapTilesLoader.TileSet.WOOD_MOTIVATOR, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.ROCK_MOTIVATOR).put((ObjectBase.ObjectSubType)subType, new RockMotivatorFlags(MapTilesLoader.TileSet.ROCK_MOTIVATOR, (ObjectBase.ObjectSubType)subType));
            this.objectFlags.get((Object)MapTilesLoader.TileSet.VEGETABLE_MOTIVATOR).put((ObjectBase.ObjectSubType)subType, new VegetableMotivatorFlags(MapTilesLoader.TileSet.VEGETABLE_MOTIVATOR, (ObjectBase.ObjectSubType)subType));

            //@@Fine_Aggiunta_Costruttori_Flags

            ++n2;
        }
        enumArray = MapTilesLoader.TileSet.values();
        n = enumArray.length;
        n2 = 0;
        while (n2 < n) {
            type = enumArray[n2];
            if (this.objectFlags.get(type).size() == 0) {
                this.objectFlags.remove(type);
            }
            ++n2;
        }
    }

    public ObjectFlags getObjectFlags(MapTilesLoader.TileSet baseType, ObjectBase.ObjectSubType subType) {
        ObjectFlags thisObjectFlags = this.objectFlags.get((Object)baseType).get((Object)subType);
        return thisObjectFlags;
    }

    public HashMap<MapTilesLoader.TileSet, HashMap<ObjectBase.ObjectSubType, ObjectFlags>> getObjectFlagsList() {
        return this.objectFlags;
    }
}

